### ISSUE TITLE
Browserify build failing

### ISSUE THREAD

**Issue by HarshKhandeparkar** [gpujs/benchmark#7]
```console
/mnt/Data/.githubProjects/gpujs/benchmark/build.js:7
    if (err) throw err;
             ^

Error: Cannot find module './utils' from '/mnt/Data/.githubProjects/gpujs/benchmark/node_modules/gpu.js/dist'
    at /mnt/Data/.githubProjects/gpujs/benchmark/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/mnt/Data/.githubProjects/gpujs/benchmark/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/mnt/Data/.githubProjects/gpujs/benchmark/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /mnt/Data/.githubProjects/gpujs/benchmark/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
```

**Comment by HarshKhandeparkar** [comment]
@robertleeplummerjr

**Comment by HarshKhandeparkar** [comment]
temporarily removed dist for the next minor
